# python-api-challenge
Was having no issues til it got to mapping. I see no errors but for someone reason the info won't save into the city_data list. 
